language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - aitorbernalfalcon95@gmail.com
script:
#Test unitario y de integracion en develop
mvn clean -Denvironment.type=develop --settings settings.xml
mvn test -Denvironment.type=develop --settings settings.xml
